/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * linechart.java
 *
 * Created on Mar 27, 2013, 2:23:52 PM
 */
package vn.com.hkt.gui.chart.PanelShow;

import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.time.TimeSeriesCollection;
import vn.com.hkt.data.entity.Department;
import vn.com.hkt.data.entity.Employee;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.data.entity.Project;
import vn.com.hkt.gui.chart.panelshow.api.IPanelShowChart;
import vn.com.hkt.statistic.chart.DepartmentStatisticChart;
import vn.com.hkt.statistic.chart.EmployeeStatisticChart;
import vn.com.hkt.statistic.chart.EnterpriseStatisticChart;
import vn.com.hkt.statistic.chart.ProjectStatisticChart;

/**
 *
 * @author Administrator
 */
public final class linechart extends javax.swing.JPanel implements IPanelShowChart {

    /** Creates new form linechart */
    Enterprise e;
    Department d;
    Project p;
    Employee emp;
    int typeView;
    int typeDate;
    Date startDate;
    Date endDate;
    EnterpriseStatisticChart enterpriseChart;
    DepartmentStatisticChart departmentChart;
    ProjectStatisticChart projectChart;
    EmployeeStatisticChart employeeChart;
    public linechart() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
    public  ChartPanel createChart(){
        TimeSeriesCollection dataset=new TimeSeriesCollection();
        if(e!=null){
            dataset= (TimeSeriesCollection) enterpriseChart.createDataset(typeDate,typeView,e.getId(),startDate,endDate);
                       dataset= (TimeSeriesCollection) enterpriseChart.createDataset(typeDate,typeView,e.getId(),startDate,endDate);
        }else if(d !=null){
            //dataset=(TimeSeriesCollection) departmentChart.createDataset(typeDate, typeView, d.getId(), d.getIdEnterprise(), startDate, endDate);
        }else if(p !=null){
           // dataset=(TimeSeriesCollection) projectChart.createDataset(typeDate,p.getId(), p.getIdDepartment(), p.getIdEnterprise(), startDate, endDate);
        }else if(emp !=null){
           // dataset=(TimeSeriesCollection) employeeChart.createDataset(typeDate, emp.getId(), startDate, endDate);
        }else{
            JOptionPane.showMessageDialog(null, "Data not found");
            return null;
        }
        
        JFreeChart chart=ChartFactory.createTimeSeriesChart("Chart "+e.getName(), "Year","Money" , dataset, true, true, false);
        //design
//        chart.setBackgroundPaint(Color.white);
//        CategoryPlot plot = (CategoryPlot) chart.getPlot();
//        plot.setBackgroundPaint(Color.lightGray);
//        plot.setRangeGridlinePaint(Color.white);
//        // customise the range axis...
//        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
//        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
//        // customise the renderer...
//        LineAndShapeRenderer renderer = (LineAndShapeRenderer) plot.getRenderer();
//        renderer.setShapesVisible(true);
//        renderer.setDrawOutlines(true);
//        renderer.setUseFillPaint(true);
//        renderer.setFillPaint(Color.white);
        //xuat ra form
        ChartPanel panel=new ChartPanel(chart);
        return panel;
    }

    @Override
    public void setControlShow() {
      //  throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setObjectView(Object obj) {
      if(obj instanceof Enterprise){
          e=(Enterprise) obj;
      }else if(obj instanceof Department){
          d=(Department)obj;
      }else if(obj instanceof Project){
          p=(Project)obj;
      }else{
          emp=(Employee)obj;
      }
    }

    @Override
    public void setTypeDate(int type) {
        this.typeDate=type;   
    }

    @Override
    public void setTypeView(int type) {
      this.typeView=type;
    }

    @Override
    public void setStartDate(Date d) {
      this.startDate=d;
    }

    @Override
    public void setEndDate(Date d) {
       this.endDate=d;
    }

    @Override
    public void viewData() {
       jScrollPane1.setViewportView(createChart());
    }
}
