/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewProject.java
 *
 * Created on Mar 14, 2013, 11:37:05 AM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import vn.com.hkt.data.entity.Department;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.gui.entity.api.IPanelShowList;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowEnterprise;
import vn.com.hkt.provider.api.IProviderPanelShowListDepartment;
import vn.com.hkt.provider.api.IProviderPanelShowListEnterprise;
import vn.com.hkt.provider.api.IProviderPanelShowProject;
import vn.com.hkt.provider.spi.ProviderPanelShowListDepartment;
import vn.com.hkt.provider.spi.ProviderPanelShowListEnterprise;
import vn.com.hkt.provider.spi.ProviderPanelShowProject;

/**
 *
 * @author Administrator
 */
public class AddNewProject extends javax.swing.JPanel implements IPanelShowList, IShowPanel<Object> {
    private long departmentID;
    private long enterpriseID;
    private IProviderPanelShowProject provider;
    private IProviderPanelShowListEnterprise providerEnterprise;
    private IProviderPanelShowListDepartment providerDepartment;

    /** Creates new form AddNewProject */
    public AddNewProject() {
        initComponents();
        provider=new ProviderPanelShowProject();
        providerEnterprise = new ProviderPanelShowListEnterprise();
        providerDepartment=new ProviderPanelShowListDepartment();
//        loadComboxEnterprise();
//        loadComboxDepartment();
        showDefault();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        dateEnd = new com.toedter.calendar.JDateChooser();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox();
        cbDepartment = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add New Project");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Description :");
        add(jLabel5);
        jLabel5.setBounds(90, 250, 140, 23);
        add(txtProjectName);
        txtProjectName.setBounds(260, 50, 200, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Project name :");
        add(jLabel6);
        jLabel6.setBounds(90, 50, 140, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Date start :");
        add(jLabel7);
        jLabel7.setBounds(90, 90, 140, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Enterprise :");
        add(jLabel8);
        jLabel8.setBounds(90, 210, 140, 23);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 290, 370, 100);
        add(dateEnd);
        dateEnd.setBounds(260, 130, 200, 23);
        add(dateStart);
        dateStart.setBounds(260, 90, 200, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Date end :");
        add(jLabel9);
        jLabel9.setBounds(90, 130, 140, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Department :");
        add(jLabel10);
        jLabel10.setBounds(90, 170, 140, 23);

        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbEnterprise);
        cbEnterprise.setBounds(260, 210, 200, 23);

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepartmentItemStateChanged(evt);
            }
        });
        add(cbDepartment);
        cbDepartment.setBounds(260, 170, 200, 23);
    }// </editor-fold>//GEN-END:initComponents

private void cbDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartmentItemStateChanged
    Department d=(Department)cbDepartment.getSelectedItem();
    departmentID=d.getId();
    Enterprise e=(Enterprise)cbEnterprise.getSelectedItem();
    enterpriseID=e.getId();
    
}//GEN-LAST:event_cbDepartmentItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDepartment;
    private javax.swing.JComboBox cbEnterprise;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtProjectName;
    // End of variables declaration//GEN-END:variables

//    private void loadComboxEnterprise() {
//        cbEnterprise.setModel(new DefaultComboBoxModel(listCombo().toArray()));
//    }
    @Override
    public void showDefault() {
        loadComboxEnterprise();
        loadComboxDepartment();
    }

    private void loadComboxEnterprise() {
        List<Enterprise> enterprises = providerEnterprise.getListInformation();
        cbEnterprise.setModel(new DefaultComboBoxModel(enterprises.toArray()));
    }

    private void loadComboxDepartment() {
        List<Department> departments = providerDepartment.getListInformation();
        cbDepartment.setModel(new DefaultComboBoxModel(departments.toArray()));
    }

    @Override
    public List<Object> listA() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean checkData() {
        if (txtProjectName.getText().length() == 0) {
            return false;
        }
        if (dateEnd.getDate() == null) {
            return false;
        }
        if (dateStart.getDate() == null) {
            return false;
        }
        return true;
    }

    @Override
    public long addData() {
        if (!checkData() || !getData()) {
            return -1;
        } else {
            return provider.addData();
        }
    }

    @Override
    public boolean editData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean deleteData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<Object> listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private boolean getData() {
        try {
            provider.getDataView().setName(txtProjectName.getText());
            provider.getDataView().setDateEnd(dateEnd.getDate());
            provider.getDataView().setDateStart(dateStart.getDate());
            provider.getDataView().setDescript(txtDescription.getText());
            provider.getDataView().setIdDepartment(departmentID);
            provider.getDataView().setIdEnterprise(enterpriseID);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}
