/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewOperation.java
 *
 * Created on Mar 20, 2013, 11:45:00 AM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import vn.com.hkt.data.entity.Department;
import vn.com.hkt.data.entity.Employee;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.data.entity.Operation;
import vn.com.hkt.data.entity.Project;
import vn.com.hkt.data.entity.UnitMoney;
import vn.com.hkt.gui.control.api.IPanelControlGeneral;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowOperation;
import vn.com.hkt.provider.spi.ProviderPanelShowOperation;

/**
 *
 * @author Administrator
 */
public class AddNewOperation extends javax.swing.JPanel implements IShowPanel<Operation> {

    private long departmentID;
    private long enterpriseID;
    private long projectID;
    private long employeeID;
    private long unitMoneyID;
    private IProviderPanelShowOperation provider;
    /** Creates new form AddNewOperation */
    public AddNewOperation() {
        initComponents();
        provider=new ProviderPanelShowOperation();
        loadEnterprise();
        loadUnitMoney();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbUnitMoney = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbDepartment = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbEmployee = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        cbProject = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        lbError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add New Operation");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 200, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Classification :");
        add(jLabel6);
        jLabel6.setBounds(90, 460, 150, 23);

        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEnterpriseItemStateChanged(evt);
            }
        });
        add(cbEnterprise);
        cbEnterprise.setBounds(240, 100, 200, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Code :");
        add(jLabel5);
        jLabel5.setBounds(90, 60, 150, 23);

        cbUnitMoney.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbUnitMoney.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUnitMoneyItemStateChanged(evt);
            }
        });
        add(cbUnitMoney);
        cbUnitMoney.setBounds(240, 420, 200, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Choose department :");
        add(jLabel7);
        jLabel7.setBounds(90, 140, 150, 23);

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepartmentItemStateChanged(evt);
            }
        });
        add(cbDepartment);
        cbDepartment.setBounds(240, 140, 200, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Choose employee :");
        add(jLabel8);
        jLabel8.setBounds(90, 180, 150, 23);

        cbEmployee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEmployee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmployeeItemStateChanged(evt);
            }
        });
        add(cbEmployee);
        cbEmployee.setBounds(240, 180, 200, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Choose project :");
        add(jLabel9);
        jLabel9.setBounds(90, 220, 150, 23);
        add(jTextField1);
        jTextField1.setBounds(240, 340, 200, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Money total :");
        add(jLabel10);
        jLabel10.setBounds(90, 260, 150, 23);
        add(jTextField2);
        jTextField2.setBounds(240, 60, 200, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Money after tax :");
        add(jLabel11);
        jLabel11.setBounds(90, 300, 150, 23);
        add(jTextField3);
        jTextField3.setBounds(240, 300, 200, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Choose enterprise :");
        add(jLabel12);
        jLabel12.setBounds(90, 100, 150, 23);
        add(jTextField4);
        jTextField4.setBounds(240, 260, 200, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Money after discount :");
        add(jLabel13);
        jLabel13.setBounds(90, 340, 150, 23);
        add(jDateChooser1);
        jDateChooser1.setBounds(240, 380, 200, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Date execute :");
        add(jLabel14);
        jLabel14.setBounds(90, 380, 150, 23);

        cbProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProjectItemStateChanged(evt);
            }
        });
        add(cbProject);
        cbProject.setBounds(240, 220, 200, 23);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Unit money :");
        add(jLabel15);
        jLabel15.setBounds(90, 420, 150, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Sale");
        jRadioButton1.setOpaque(false);
        add(jRadioButton1);
        jRadioButton1.setBounds(340, 460, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Buy");
        jRadioButton2.setOpaque(false);
        add(jRadioButton2);
        jRadioButton2.setBounds(240, 460, 100, 23);

        lbError.setForeground(new java.awt.Color(255, 0, 0));
        add(lbError);
        lbError.setBounds(240, 500, 300, 23);
    }// </editor-fold>//GEN-END:initComponents

private void cbEnterpriseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEnterpriseItemStateChanged
    loadCBEnterprise();
}//GEN-LAST:event_cbEnterpriseItemStateChanged

private void cbUnitMoneyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUnitMoneyItemStateChanged
    loadCBUnitMoney();
}//GEN-LAST:event_cbUnitMoneyItemStateChanged

private void cbDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartmentItemStateChanged
    loadCBDepartment();
}//GEN-LAST:event_cbDepartmentItemStateChanged

private void cbEmployeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmployeeItemStateChanged
    loadCBEmployee();
}//GEN-LAST:event_cbEmployeeItemStateChanged

private void cbProjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProjectItemStateChanged
    loadCBProject();
}//GEN-LAST:event_cbProjectItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbDepartment;
    private javax.swing.JComboBox cbEmployee;
    private javax.swing.JComboBox cbEnterprise;
    private javax.swing.JComboBox cbProject;
    private javax.swing.JComboBox cbUnitMoney;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbError;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlShow(IPanelControlGeneral controlGeneral) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<Operation> listA() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean checkData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public long addData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean resetData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean editData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean deleteData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<Operation> listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setDataShow(Operation ob) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void refreshData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    private void loadEnterprise() {
        List<Enterprise> enterprises = provider.getListEnterprise();
        if (enterprises != null) {
            cbEnterprise.setModel(new DefaultComboBoxModel(enterprises.toArray()));
            loadCBEnterprise();
        } else {
            lbError.setText("No enterprise");
        }
    }

    private void loadDepartment() {
        if (enterpriseID > 0) {
            List<Department> departments = provider.getListDepartmentByIDEnt(enterpriseID);
            cbDepartment.setModel(new DefaultComboBoxModel(departments.toArray()));
        } else {
            cbDepartment.enable(false);
        }
    }

    private void loadCBEnterprise() {
        Enterprise e = (Enterprise) cbEnterprise.getSelectedItem();
        if (e != null) {
            if (e.getId() > 0) {
                cbProject.setEnabled(true);
                cbDepartment.setEnabled(true);
                enterpriseID = e.getId();
                loadDepartment();
                loadProject();
                loadCBDepartment();
                loadCBProject();
            } else {
                enterpriseID = 0;
            }
        } else {
            cbProject.setEnabled(false);
            cbDepartment.setEnabled(false);
            cbEmployee.setEnabled(false);
        }
    }

    private void loadCBDepartment() {
        int index = cbEnterprise.getSelectedIndex();
        if (index > 0) {
            Department d = (Department) cbDepartment.getSelectedItem();
            if (d != null) {
                if (d.getId() > 0) {
                    cbEmployee.setEnabled(true);
                    departmentID = d.getId();
                    loadEmployee();
                    loadCBEmployee();
                } else {
                    departmentID = 0;
                }
            } else {
                cbEmployee.setEnabled(false);
                departmentID = 0;
            }
        } else {
            departmentID = 0;
        }
    }
    private void loadUnitMoney() {
        List<UnitMoney> unitMoneys = provider.getListUnitMoney();
        if (unitMoneys != null) {
            cbUnitMoney.setModel(new DefaultComboBoxModel(unitMoneys.toArray()));
            loadCBUnitMoney();
        } else {
            lbError.setText("No unit money");
        }
    }

    private void loadCBUnitMoney() {
        UnitMoney u = (UnitMoney) cbUnitMoney.getSelectedItem();
        if (u != null) {
            if (u.getId() > 0) {
                unitMoneyID = u.getId();
            } else {
                unitMoneyID = 0;
            }
        } 
    }
    
    private void loadEmployee() {
        if (departmentID > 0) {
            List<Employee> employees = provider.getListEmployeeByIDDep(departmentID);
            cbEmployee.setModel(new DefaultComboBoxModel(employees.toArray()));
        } else {
            cbEmployee.enable(false);
        }
    }

    private void loadCBEmployee() {
        int index = cbDepartment.getSelectedIndex();
        if (index > 0) {
            Employee e = (Employee) cbEmployee.getSelectedItem();
            if (e != null) {
                if (e.getId() > 0) {
                    employeeID = e.getId();
                } else {
                    employeeID = 0;
                }
            } else {
                employeeID = 0;
            }
        } else {
            employeeID = 0;
        }
    }
    
    private void loadProject(){
        if (enterpriseID > 0) {
            JOptionPane.showMessageDialog(null, enterpriseID);
            List<Project> projects = provider.getListProjectByIDEnt(enterpriseID);
            cbProject.setModel(new DefaultComboBoxModel(projects.toArray()));
        } else {
            cbProject.enable(false);
        }
    }

    private void loadCBProject() {
        int index = cbEnterprise.getSelectedIndex();
        if (index > 0) {
            Project p = (Project) cbProject.getSelectedItem();
            if (p != null) {
                if (p.getId() > 0) {
                    projectID = p.getId();
                } else {
                    projectID = 0;
                }
            } else {
                projectID = 0;
            }
        } else {
            projectID = 0;
        }
    }
}
