/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewProductGroup.java
 *
 * Created on Mar 20, 2013, 9:34:16 AM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.data.entity.ProductGroup;
import vn.com.hkt.gui.entity.api.IPanelShowList;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowListEnterprise;
import vn.com.hkt.provider.api.IProviderPanelShowListProductGroup;
import vn.com.hkt.provider.api.IProviderPanelShowProductGroup;
import vn.com.hkt.provider.spi.ProviderPanelShowListEnterprise;
import vn.com.hkt.provider.spi.ProviderPanelShowListProductGroup;
import vn.com.hkt.provider.spi.ProviderPanelShowProductGroup;

/**
 *
 * @author Administrator
 */
public class AddNewProductGroup extends javax.swing.JPanel implements IShowPanel, IPanelShowList {

    private IProviderPanelShowListEnterprise providerEnterprise;
    private IProviderPanelShowListProductGroup providerGroup;
    private long groupID;
    private long enterpriseID;
    private IProviderPanelShowProductGroup provider;

    /** Creates new form AddNewProductGroup */
    public AddNewProductGroup() {
        initComponents();
        provider = new ProviderPanelShowProductGroup();
        providerEnterprise = new ProviderPanelShowListEnterprise();
        providerGroup = new ProviderPanelShowListProductGroup();
        showDefault();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox();
        cbGroup = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        setLayout(null);
        add(txtName);
        txtName.setBounds(290, 140, 200, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Choose parent group :");
        add(jLabel6);
        jLabel6.setBounds(120, 100, 150, 23);

        lbError.setFont(new java.awt.Font("Tahoma", 0, 12));
        lbError.setForeground(new java.awt.Color(255, 0, 51));
        add(lbError);
        lbError.setBounds(290, 220, 200, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Choose enterprise :");
        add(jLabel5);
        jLabel5.setBounds(120, 60, 150, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Code :");
        add(jLabel7);
        jLabel7.setBounds(120, 180, 150, 23);

        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEnterpriseItemStateChanged(evt);
            }
        });
        add(cbEnterprise);
        cbEnterprise.setBounds(290, 60, 200, 23);

        cbGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGroupItemStateChanged(evt);
            }
        });
        add(cbGroup);
        cbGroup.setBounds(290, 100, 200, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add New Product Group");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 240, 23);
        add(txtCode);
        txtCode.setBounds(290, 180, 200, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Group name :");
        add(jLabel8);
        jLabel8.setBounds(120, 140, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

private void cbEnterpriseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEnterpriseItemStateChanged
    loadCBEnterprise();
}//GEN-LAST:event_cbEnterpriseItemStateChanged
    private void loadCBEnterprise() {
        Enterprise e = (Enterprise) cbEnterprise.getSelectedItem();
        if (e != null) {   
            if (e.getId() > 0) {
                System.out.println("----------------"+e.getId());
                cbGroup.setEnabled(true);
                enterpriseID = e.getId();
                System.out.println("+++++"+enterpriseID);
                loadGroup();
                loadCBGroup();
            } else {
                enterpriseID = 0;
            }
        } else {
            cbGroup.setEnabled(false);
        }
    }
private void cbGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGroupItemStateChanged
    loadCBGroup();
}//GEN-LAST:event_cbGroupItemStateChanged
    private void loadCBGroup() {
        int index = cbEnterprise.getSelectedIndex();
        if (index > 0) {
            ProductGroup d = (ProductGroup) cbGroup.getSelectedItem();
            if (d != null) {
                if (d.getId() > 0) {
                    groupID = d.getId();
                } else {
                    groupID = 0;
                }
            } else {
                groupID = 0;
            }
        } else {
            groupID = 0;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbEnterprise;
    private javax.swing.JComboBox cbGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public List listA() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean checkData() {
        if(txtName.getText().length()==0){
            lbError.setText("Enter group name");
            return false;
        }
        if(txtCode.getText().length()==0){
            lbError.setText("Enter group code");
            return false;
        }
        if (cbEnterprise.getSelectedIndex() == 0) {
            lbError.setText("Choose enterprise !");
            return false;
        }
        return true;
    }

    @Override
    public long addData() {
        if(!checkData()||!getData()){
            return 0;
        }
        return provider.addData();
    }

    @Override
    public boolean editData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean deleteData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void showDefault() {
        loadEnterprise();
    }

    private void loadEnterprise() {
        List<Enterprise> enterprises = providerEnterprise.getListInformation();
        if (enterprises != null) {
            cbEnterprise.setModel(new DefaultComboBoxModel(enterprises.toArray()));
            loadCBEnterprise();
        } else {
            enterpriseID = 0;
        }
    }

    private void loadGroup() {
        if (enterpriseID > 0) {
            List<ProductGroup> groups = providerGroup.getByIdEnterprise(enterpriseID);
            cbGroup.setModel(new DefaultComboBoxModel(groups.toArray()));
        } else {
            cbGroup.enable(false);
        }
    }

    private boolean getData() {
        provider.getDataView().setName(txtName.getText());
        provider.getDataView().setCodeProductGroup(txtCode.getText());
        provider.getDataView().setIdEnterprise(enterpriseID);
        provider.getDataView().setIdProductGroup(groupID);
        return true;
    }

    @Override
    public boolean resetData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
