/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewEmployee.java
 *
 * Created on Mar 14, 2013, 11:02:28 AM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import vn.com.hkt.data.entity.Department;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.gui.entity.api.IPanelShowList;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowEmployee;
import vn.com.hkt.provider.api.IProviderPanelShowListDepartment;
import vn.com.hkt.provider.api.IProviderPanelShowListEnterprise;
import vn.com.hkt.provider.spi.ProviderPanelShowEmployee;
import vn.com.hkt.provider.spi.ProviderPanelShowListDepartment;
import vn.com.hkt.provider.spi.ProviderPanelShowListEnterprise;

/**
 *
 * @author Administrator
 */
public class AddNewEmployee extends javax.swing.JPanel implements IShowPanel,IPanelShowList{
    
    private IProviderPanelShowListEnterprise providerEnterprise;
    private IProviderPanelShowListDepartment providerDepartment;
    private long departmentID;
    private long enterpriseID;
    private IProviderPanelShowEmployee provider;
    /** Creates new form AddNewEmployee */
    public AddNewEmployee() {
        initComponents();
        provider=new ProviderPanelShowEmployee();
        providerEnterprise = new ProviderPanelShowListEnterprise();
        providerDepartment = new ProviderPanelShowListDepartment();
        showDefault();
        loadCBEnterprise();
        loadCBDepartment();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbDepartment = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbEnterprise = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        lbError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Add New Employee");
        add(jLabel1);
        jLabel1.setBounds(22, 12, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Employee name :");
        add(jLabel4);
        jLabel4.setBounds(102, 212, 140, 23);

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepartmentItemStateChanged(evt);
            }
        });
        add(cbDepartment);
        cbDepartment.setBounds(262, 172, 196, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Choose enterprise :");
        add(jLabel5);
        jLabel5.setBounds(102, 132, 140, 23);

        cbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbEnterprise.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEnterpriseItemStateChanged(evt);
            }
        });
        add(cbEnterprise);
        cbEnterprise.setBounds(262, 132, 196, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Choose department :");
        add(jLabel6);
        jLabel6.setBounds(102, 172, 140, 23);
        add(txtEmployeeName);
        txtEmployeeName.setBounds(262, 212, 196, 23);

        lbError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbError.setForeground(new java.awt.Color(255, 0, 51));
        add(lbError);
        lbError.setBounds(262, 252, 250, 23);
    }// </editor-fold>//GEN-END:initComponents

private void cbEnterpriseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEnterpriseItemStateChanged
        loadCBEnterprise();
}//GEN-LAST:event_cbEnterpriseItemStateChanged

private void cbDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartmentItemStateChanged
        loadCBDepartment();
}//GEN-LAST:event_cbDepartmentItemStateChanged

    private void loadCBDepartment() {
        Department d=(Department) cbDepartment.getSelectedItem();
        if(d.getId()>0){
            departmentID=d.getId();
        }else{
            departmentID=0;
        }
    }

    private void loadCBEnterprise() {
        Enterprise e = (Enterprise) cbEnterprise.getSelectedItem();
            if (e.getId() >0) {
                enterpriseID = e.getId();
            }else{
                enterpriseID=0;
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDepartment;
    private javax.swing.JComboBox cbEnterprise;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbError;
    private javax.swing.JTextField txtEmployeeName;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean checkData() {
        if(txtEmployeeName.getText().length()==0){
            lbError.setText("Enter employee name !");
            return false;
        }
        return true;
    }

    @Override
    public long addData() {
        if(!checkData() || ! getData()){
            lbError.setText("Wrong error !");
            return 0;
        }
        return provider.addData();
    }

    @Override
    public boolean editData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean deleteData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List listA() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void showDefault() {
        loadDepartment();
        loadEnterprise();
        
    }

    private void loadEnterprise() {
        List<Enterprise> enterprises = providerEnterprise.getListInformation();
        cbEnterprise.setModel(new DefaultComboBoxModel(enterprises.toArray()));
    }

    private void loadDepartment() {
       List<Department> departments = providerDepartment.getListInformation();
       cbDepartment.setModel(new DefaultComboBoxModel(departments.toArray()));
    }

    private boolean getData() {
       provider.getDataView().setName(txtEmployeeName.getText());
       provider.getDataView().setIdDepartment(departmentID);
       return true;
    }
}
