/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowEnterprise.java
 *
 * Created on Mar 14, 2013, 2:09:59 PM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.Date;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowEnterprise;
import vn.com.hkt.provider.spi.ProviderPanelShowEnterprise;

/**
 *
 * @author Administrator
 */
public class PanelShowEnterprise extends javax.swing.JPanel implements IShowPanel {

    private IProviderPanelShowEnterprise provider;

    /** Creates new form PanelShowEnterprise */
    public PanelShowEnterprise() {
        initComponents();
        provider = new ProviderPanelShowEnterprise();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();

        jLabel1.setText("Ten doanh nghiep");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtEnterpriseName, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEnterpriseName;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean checkData() {
        if (txtEnterpriseName.getText().length() == 0) {
            return false;
        }
        return true;
    }

    @Override
    public long addData() {
        if (!checkData() || !getData()) {
            return -1;
        } else {
            return provider.addData();
        }
    }

    @Override
    public boolean editData() {
        return true;
    }

    @Override
    public boolean deleteData() {
        return true;
    }

    private boolean getData() {
        try {
            provider.getDataView().setName(txtEnterpriseName.getText());
            provider.getDataView().setDateActivative(new Date());
            return true;
        } catch (Exception e) {
            return false;
        }
    }
}
