/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowAllParentEnterprise.java
 *
 * Created on Mar 14, 2013, 3:12:27 PM
 */
package vn.com.hkt.gui.panel.spi;

import vn.com.hkt.gui.panel.model.spi.MyButton;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import vn.com.hkt.dao.api.IEnterpriseDao;
import vn.com.hkt.dao.spi.EnterpriseDao;
import vn.com.hkt.data.entity.Enterprise;
import vn.com.hkt.gui.entity.api.IShowPanel;

/**
 *
 * @author Administrator
 */
public class PanelShowAllParentEnterprise extends javax.swing.JPanel implements IShowPanel<Enterprise> {

    /** Creates new form PanelShowAllParentEnterprise */
    private IEnterpriseDao provider;
//    private List<Enterprise> listEnterprises;
//    public void setLisFtEnterprises(List<Enterprise> listEnterprises) {
//        this.listEnterprises = listEnterprises;
//    }
    public PanelShowAllParentEnterprise() {
        initComponents();
        this.setLayout(new FlowLayout());
        provider = new EnterpriseDao();
        System.out.println(""+listA());
        for(Enterprise en:listA()){
            MyButton b=new MyButton();
            b.setEn(en);
            b.setPreferredSize(new Dimension(140, 30));
            b.setBackground(Color.lightGray);
            b.setText(en.getName());
            b.setBorder(BorderFactory.createLineBorder(Color.orange));
            this.add(b);
        }
//        for(Enterprise en:listEnterprises){
//            JButton b=new JButton();
//            b.setText(en.getName());
//            this.add(b);
//        }
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean checkData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public long addData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean editData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean deleteData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<Enterprise> listA() {
        return provider.getListByIdEnterprise(1);
    }

    @Override
    public List<Enterprise> listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
