/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelShowInsertEnterprise.java
 *
 * Created on Mar 14, 2013, 2:09:59 PM
 */
package vn.com.hkt.gui.panel.spi;

import java.util.Date;
import java.util.List;
import vn.com.hkt.gui.entity.api.IShowPanel;
import vn.com.hkt.provider.api.IProviderPanelShowEnterprise;
import vn.com.hkt.provider.spi.ProviderPanelShowEnterprise;

/**
 *
 * @author Administrator
 */
public class PanelShowInsertEnterprise extends javax.swing.JPanel implements IShowPanel {

    private IProviderPanelShowEnterprise provider;

    /** Creates new form PanelShowInsertEnterprise */
    public PanelShowInsertEnterprise() {
        initComponents();
        provider = new ProviderPanelShowEnterprise();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEnterpriseName = new javax.swing.JTextField();
        txtParentID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        setForeground(new java.awt.Color(51, 51, 51));
        setLayout(null);
        add(txtEnterpriseName);
        txtEnterpriseName.setBounds(280, 110, 200, 23);
        add(txtParentID);
        txtParentID.setBounds(280, 150, 200, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Add New Enterprise");
        add(jLabel3);
        jLabel3.setBounds(20, 10, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Picture :");
        add(jLabel4);
        jLabel4.setBounds(110, 230, 140, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Enterprise name :");
        add(jLabel5);
        jLabel5.setBounds(110, 110, 140, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Slogan :");
        add(jLabel6);
        jLabel6.setBounds(110, 150, 140, 23);
        add(jDateChooser1);
        jDateChooser1.setBounds(280, 190, 200, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Date active  :");
        add(jLabel7);
        jLabel7.setBounds(110, 190, 140, 23);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtParentID;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean checkData() {
        if (txtEnterpriseName.getText().length() == 0) {
            return false;
        }
        return true;
    }

    @Override
    public long addData() {
        if (!checkData() || !getData()) {
            return -1;
        } else {
            return provider.addData();
        }
    }

    @Override
    public boolean editData() {
        return true;
    }

    @Override
    public boolean deleteData() {
        return true;
    }

    private boolean getData() {
        try {
            provider.getDataView().setName(txtEnterpriseName.getText());
            provider.getDataView().setDateActivative(new Date());
            provider.getDataView().setIdEnterprise(Integer.parseInt(txtParentID.getText()));
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public List listA() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List listCombo() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
